### ISSUE TITLE
FR - Improve beat schema for the file.path

### ISSUE THREAD

**Issue by initharrington** [Ardiea/fileagebeat#5]
### Description
The file.path shows the fully qualified path of the each file that is detected (including the file name).  Can there be a separate field that is part of the schema that shows the path of the folder (the path that is inputed in the configuration).

This will allow aggregation around the "path" instead of input "name".

This could be done with logstash, but I don't think that is the correct approach.

### Motivation
Improve document data for reporting

### Am I planning to do it myself with a PR?
No, but I can if you want me to.

**Comment by Ardiea** [comment]
Added file.directory (string) and file.age (string) with v7.5.1-3
```
{
  "@timestamp": "2020-01-29T15:33:19.054Z",
  "@metadata": {
    "beat": "fileagebeat",
    "type": "_doc",
    "version": "7.5.1"
  },
  "fields": {
    "bt_customer": "test_customer",
    "bt_tier": "pr"
  },
  "ecs": {
    "version": "1.1.0"
  },
  "host": {
    "name": "vm01"
  },
  "event": {
    "action": "aging_file_found"
  },
  "file": {
    "size": 350,
    "mode": "-rw-rw-r--",
    "path": "/home/mdavidson/code/beats/packetbeat/tests/system/pcaps/dns_additional.pcap",
    "directory": "/home/mdavidson/code/beats/packetbeat/tests/system/pcaps",
    "age": "1316h22m8s",
    "mtime": "2019-10-17T17:34:27.171Z",
    "atime": "2019-12-05T19:11:11.349Z",
    "ctime": "2019-10-17T17:34:27.171Z"
  },
  "agent": {
    "name": "perf_test4",
    "hostname": "vm01",
    "id": "b87a9acf-7d99-4121-95e8-54a78b47bc38",
    "version": "7.5.1",
    "type": "fileagebeat",
    "ephemeral_id": "5cddb5a6-6cf3-4173-a645-04f0fa6dd111"
  }
}
```
